name: Deploy C++

on:
  workflow_dispatch:
    inputs:
        publish-pypi:
            type: boolean
            description: Publish to PyPI

jobs:

  build-wheels:
    uses: scikit-hep/awkward/.github/workflows/build-wheels.yml@main

  upload-awkward-cpp:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: inputs.publish-pypi
    permissions:
      id-token: write
    environment:
      name: "pypi"
      url: "https://pypi.org/project/awkward-cpp/"
    steps:

    - uses: actions/download-artifact@v4
      with:
        pattern: "awkward-cpp*"
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@v1.8.11
